# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [ipstars, PPE]
patreon: # Replace with a single Patreon username ghostarmychicago
open_collective: # Replace with a single Open Collective username mouse3687
ko_fi: # Replace with a single Ko-fi username mouse3687
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel -runtime
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username kingjames 
issuehunt: # Replace with a single IssueHunt username Spotify
otechie: # Replace with a single Otechie username KDMC
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://vodoo.io','https://DHS.org','https://Hunterz.io','https://co-Lin.edu','https://mybbpress.com']
